const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const root = path.join(__dirname, '..');
const html = fs.readFileSync(path.join(root, 'index.html'), 'utf8');
const app = fs.readFileSync(path.join(root, 'js', 'app.js'), 'utf8');
const inDb = fs.readFileSync(path.join(root, 'js', 'inDB', 'inDB.js'), 'utf8');
const css = fs.readFileSync(path.join(root, 'js', 'inDB', 'inDB.css'), 'utf8');
const internalImageApp = fs.readFileSync(path.join(root, 'js', 'internal-image-app.js'), 'utf8');

assert.match(html, /js\/inDB\/inDB\.css/);
assert.match(html, /js\/inDB\/inDB\.js/);
assert.doesNotMatch(html, /id="indb-status-modal"/, 'inDB 모달 마크업은 전용 모듈에서 관리해야 합니다.');
assert.doesNotMatch(html, /id="indb-backup-prefix-settings-card"/, 'inDB 설정 카드는 전용 모듈에서 관리해야 합니다.');
assert.doesNotMatch(html, /id="btn-open-indb-status"/, 'inDB 설정 버튼은 전용 모듈에서 관리해야 합니다.');
assert.doesNotMatch(html, /id="btn-footer-open-indb-status"/, 'inDB 푸터 버튼은 전용 모듈에서 관리해야 합니다.');
assert.match(inDb, /id="btn-open-indb-status/);
assert.match(inDb, /id="btn-footer-open-indb-status/);
assert.match(inDb, /id="indb-status-panel"[^>]*class="indb-status-panel"/);
assert.match(inDb, /id="btn-open-indb-images-fma"[^>]*onclick="openAllInDbImagesInFmaViewer\(\)"/);
assert.match(inDb, /id="btn-clean-unused-indb-images"[^>]*onclick="deleteUnusedInDbImages\(\)"/);
assert.match(inDb, /id="indb-unused-image-modal"/);
assert.match(inDb, />전체 선택<\/button>[\s\S]*?>전체 해제<\/button>/);
assert.match(inDb, /id="btn-delete-selected-unused-images"[^>]*disabled>선택 삭제 0<\/button>/);
assert.match(inDb, /id="indb-backup-prefix-input"[^>]*value="mdpro"/);
assert.match(inDb, /shortcuts\.insertAdjacentHTML\('afterend', INDB_BACKUP_PREFIX_SETTINGS_HTML\)/, '전체 파일 prefix 설정은 단축키 아래에 삽입해야 합니다.');

assert.match(inDb, /async function createInDbStatusSnapshot\(\)/);
assert.match(inDb, /extractInternalImageIdsDeep/);
assert.match(inDb, /findUnusedImageIds/);
assert.match(inDb, /async function deleteUnusedInDbImages\(\)[\s\S]*?renderUnusedInDbImageCleaner\(snapshot\)/);
assert.match(inDb, /async function deleteSelectedUnusedInDbImages\(\)[\s\S]*?db\.transaction\('images', 'readwrite'\)/);
assert.match(inDb, /function setAllUnusedInDbImagesSelected\(selected\)/);
assert.match(inDb, /class="indb-unused-checkbox"[^>]*data-id=/);
assert.match(inDb, /async function openAllInDbImagesInFmaViewer\(\)[\s\S]*?InternalImageApp\.openFiles/);
assert.match(inDb, /function dockSettingsModalForFmaViewer\(\)/);
assert.match(inDb, /layout: 'settings-left'/);
assert.match(internalImageApp, /function applyPanelLayout\(options\)/);
assert.match(internalImageApp, /opts\.layout === 'settings-left'/);
assert.match(inDb, /class="indb-record-thumb"/);
assert.match(inDb, /loading="lazy" decoding="async"/);
assert.match(inDb, /inDbStatusViewState = \{ storeName: 'documents', recordId: '' \}/, '처음 열 때 이미지 대신 문서 분류를 선택해야 합니다.');
assert.match(inDb, /class="indb-store-sidebar"/);
assert.match(inDb, /class="indb-record-pane"/);
assert.match(inDb, /class="indb-detail-pane"/);
assert.match(inDb, /function selectInDbStatusStore\(storeName\)/);
assert.match(inDb, /function selectInDbStatusRecord\(storeName, recordId\)/);
assert.doesNotMatch(inDb, /storeName === 'images' \? ' open'/, '이미지 저장소를 기본으로 펼치면 안 됩니다.');
assert.match(app, /DEFAULT_FILE_DOWNLOAD_PREFIX = 'mdpro'/);
assert.match(inDb, /return getFileDownloadPrefixFromLocal\(\) \+ '-indb-folders-'/);
assert.match(inDb, /snapshot\.referencedIds\.has\(itemId\)/, '사용 중 이미지를 개별 삭제할 때 경고해야 합니다.');
assert.match(inDb, /window\.deleteUnusedInDbImages = deleteUnusedInDbImages/);
assert.match(inDb, /window\.openAllInDbImagesInFmaViewer = openAllInDbImagesInFmaViewer/);
assert.match(inDb, /window\.InDbStorage = Object\.freeze/);

assert.match(css, /\.indb-status-panel\s*\{/);
assert.match(css, /\.dark \.indb-status-panel\s*\{/);
assert.match(css, /\.indb-overview-grid\s*\{/);
assert.match(css, /\.indb-image-grid\s*\{/);
assert.match(css, /\.indb-browser-grid\s*\{/);
assert.match(css, /\.indb-unused-grid\s*\{/);
assert.match(css, /\.indb-unused-card\.is-selected\s*\{/);
assert.match(css, /grid-template-columns:\s*minmax\(180px,[\s\S]*?minmax\(320px/);
assert.match(css, /@media \(max-width: 760px\)[\s\S]*?\.indb-status-panel/);

console.log('inDB image management and modal UI checks passed');
