const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const root = path.join(__dirname, '..');
const html = fs.readFileSync(path.join(root, 'index.html'), 'utf8');
const app = fs.readFileSync(path.join(root, 'js', 'app.js'), 'utf8');
const css = fs.readFileSync(path.join(root, 'css', 'style.css'), 'utf8');

assert.match(html, /id="litertlm-settings-body" class="hidden space-y-3"/);
assert.match(html, /id="litertlm-settings-fold-btn"[\s\S]*?aria-expanded="false"[\s\S]*?>펼치기<\/button>/);
assert.match(app, /setLiteRTLMSettingsFolded\(localStorage\.getItem\('ss_litertlm_settings_folded'\) !== '0'\)/);
assert.match(html, /id="settings-litertlm-cloud-url"[^>]*value="https:\/\/llm1\.abci\.co\.kr\/v1"/);
assert.match(html, /id="settings-litertlm-cloud-url"[^>]*readonly/);
assert.doesNotMatch(html, /id="settings-litertlm-local-mode"/);
assert.doesNotMatch(html, /id="settings-litertlm-local-url"/);
assert.match(html, /onclick="loadSettingsLiteRTLMModels\(\)"[^>]*>모델 가져오기<\/button>/);
assert.match(html, /onclick="testSettingsLiteRTLMResponse\(\)"[^>]*>연결 테스트<\/button>/);
assert.match(app, /const LITERTLM_CLOUD_BASE_URL = 'https:\/\/llm1\.abci\.co\.kr\/v1';/);
assert.match(app, /settings\.mode = 'cloud';[\s\S]*?settings\.cloudUrl = LITERTLM_CLOUD_BASE_URL;/);
assert.match(app, /const mode = 'cloud';/);
assert.doesNotMatch(html, />Base URL 기본<\/span>/);
assert.match(app, /const LITERTLM_BASE_URL_DEFAULT_MIGRATION_KEY/);
assert.match(app, /delete settings\.localUrl/);
assert.match(app, /streamLiteRTLMChat[\s\S]*?settings\.cloudUrl \|\| LITERTLM_CLOUD_BASE_URL/);
assert.match(app, /requestLiteRTLM\('\/models'/);
assert.match(app, /requestLiteRTLM\('\/chat\/completions'/);
assert.match(app, /async function requestLiteRTLM\(path, options\) \{[\s\S]*?const settings = getLiteRTLMSettings\(\);[\s\S]*?const baseUrl = normalizeLiteRTLMBaseUrl/);
assert.doesNotMatch(app, /async function requestLiteRTLM\(path, options\) \{\s*const settings = await saveLiteRTLMSettings\(false\);/);
assert.doesNotMatch(html, /gemma-4-E2B-it\.litertlm/);
assert.match(html, /<option value="">모델 가져오기를 실행하세요<\/option>/);
assert.match(app, /if \(!settings\.model\) \{[\s\S]*?await loadSettingsLiteRTLMModels\(\)/);
assert.match(app, /const LITERTLM_LEGACY_MODEL = 'gemma-4-E2B-it\.litertlm';/);
assert.match(app, /const LITERTLM_MIGRATED_MODEL = 'gemma-4-E4B';/);
assert.match(app, /settings\.model = LITERTLM_MIGRATED_MODEL;[\s\S]*?localStorage\.setItem\(LITERTLM_SETTINGS_KEY/);
assert.match(app, /const AI_PROVIDER_FOLDS_DEFAULT_VERSION_KEY = 'md_viewer_ai_provider_folds_default_v1';/);
assert.match(app, /function ensureAiProviderFoldsDefault\(\)[\s\S]*?AI_CHAT_SETTINGS_FOLD_KEY[\s\S]*?SCHOLAR_LM_SETTINGS_FOLD_KEY[\s\S]*?SCHOLAR_OLLAMA_SETTINGS_FOLD_KEY[\s\S]*?'ss_litertlm_settings_folded'/);
assert.match(app, /function collapseAiProviderSettingsForOpen\(\)[\s\S]*?setAiChatSettingsFoldedToLocal\(true\)[\s\S]*?SCHOLAR_LM_SETTINGS_FOLD_KEY, '1'[\s\S]*?SCHOLAR_OLLAMA_SETTINGS_FOLD_KEY, '1'[\s\S]*?applyAiChatSettingsFold\(true\)[\s\S]*?applyScholarLmSettingsFold\(true\)[\s\S]*?applyScholarOllamaSettingsFold\(true\)[\s\S]*?setLiteRTLMSettingsFolded\(true\)[\s\S]*?details\.open = false/);
assert.match(app, /function openSettingsModal\(\)[\s\S]*?collapseAiProviderSettingsForOpen\(\)/);
assert.match(html, /id="ai-chat-settings-fold-btn"[\s\S]*?aria-expanded="false"[\s\S]*?>펼치기<\/button>/);
assert.match(html, /id="ai-chat-settings-body" class="hidden"/);
assert.match(html, /id="ai-chat-settings"[\s\S]*?>AI JENA setting<\/p>[\s\S]*?id="ai-chat-settings-fold-btn"[\s\S]*?id="ai-chat-settings-body" class="hidden"[\s\S]*?id="ai-chat-enabled"[\s\S]*?>AI Jena 사용 \(플로팅\)<\/span>/);
assert.match(html, /<ol id="settings-gemini-models-list"[\s\S]*?aria-label="사용 가능한 Gemini 모델 목록"><\/ol>/);
assert.match(app, /function renderSettingsGeminiModels\(models\)[\s\S]*?document\.createElement\('li'\)[\s\S]*?modelList\.appendChild\(item\)/);
assert.doesNotMatch(app, /modelList\.textContent = models\.join\(' · '\)/);
assert.match(css, /#ai-link-settings-block #litertlm-settings-body\s*\{[\s\S]*?padding: 4px 18px 18px;/);
assert.match(css, /\.litertlm-save-button\s*\{[\s\S]*?background: #2563eb !important;[\s\S]*?color: #fff !important;/);
assert.match(css, /\.litertlm-parameter-grid > label\s*\{[\s\S]*?gap: 6px;/);

console.log('LiteRT-LM settings UI tests passed');
